### ISSUE TITLE
.language String method does not work on Ruby 2.4.0

### ISSUE THREAD

**Issue by jm3** [peterc/whatlanguage#44]
Instead Whatlanguage throws **undefined method `language' for "foo":String**:

    NoMethodError: undefined method `language' for "Deux autres personnes ont été arrêtées durant la nuit":String
  	from (irb):26:in `block in irb_binding'
  	from (irb):26:in `each'
  	from (irb):26
  	from ~/.rvm/rubies/ruby-2.4.0/bin/irb:11:in `<top (required)>'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/cli/exec.rb:75:in `load'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/cli/exec.rb:75:in `kernel_load'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/cli/exec.rb:28:in `run'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/cli.rb:424:in `exec'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/cli.rb:27:in `dispatch'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/cli.rb:18:in `start'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/exe/bundle:30:in `block in <top (required)>'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
  	from ~/.rvm/gems/ruby-2.4.0/gems/bundler/exe/bundle:22:in `<top (required)>'
  	from /usr/local/bin/bundle:22:in `load'
  	from /usr/local/bin/bundle:22:in `<main>'
  	from ~/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
  	from ~/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by yun-cn** [comment]
``` 
require 'whatlanguage/string'
```
